// Code generated by protoc-gen-go. DO NOT EDIT.
// source: money_transfer_command.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MoneyTransferSendRequest struct {
	// ユーザーID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 送金額
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoneyTransferSendRequest) Reset()         { *m = MoneyTransferSendRequest{} }
func (m *MoneyTransferSendRequest) String() string { return proto.CompactTextString(m) }
func (*MoneyTransferSendRequest) ProtoMessage()    {}
func (*MoneyTransferSendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_money_transfer_command_337c0a16c5e8f678, []int{0}
}
func (m *MoneyTransferSendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoneyTransferSendRequest.Unmarshal(m, b)
}
func (m *MoneyTransferSendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoneyTransferSendRequest.Marshal(b, m, deterministic)
}
func (dst *MoneyTransferSendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoneyTransferSendRequest.Merge(dst, src)
}
func (m *MoneyTransferSendRequest) XXX_Size() int {
	return xxx_messageInfo_MoneyTransferSendRequest.Size(m)
}
func (m *MoneyTransferSendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoneyTransferSendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoneyTransferSendRequest proto.InternalMessageInfo

func (m *MoneyTransferSendRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MoneyTransferSendRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MoneyTransferSendResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoneyTransferSendResponse) Reset()         { *m = MoneyTransferSendResponse{} }
func (m *MoneyTransferSendResponse) String() string { return proto.CompactTextString(m) }
func (*MoneyTransferSendResponse) ProtoMessage()    {}
func (*MoneyTransferSendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_money_transfer_command_337c0a16c5e8f678, []int{1}
}
func (m *MoneyTransferSendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoneyTransferSendResponse.Unmarshal(m, b)
}
func (m *MoneyTransferSendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoneyTransferSendResponse.Marshal(b, m, deterministic)
}
func (dst *MoneyTransferSendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoneyTransferSendResponse.Merge(dst, src)
}
func (m *MoneyTransferSendResponse) XXX_Size() int {
	return xxx_messageInfo_MoneyTransferSendResponse.Size(m)
}
func (m *MoneyTransferSendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoneyTransferSendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoneyTransferSendResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MoneyTransferSendRequest)(nil), "money.MoneyTransferSendRequest")
	proto.RegisterType((*MoneyTransferSendResponse)(nil), "money.MoneyTransferSendResponse")
}

func init() {
	proto.RegisterFile("money_transfer_command.proto", fileDescriptor_money_transfer_command_337c0a16c5e8f678)
}

var fileDescriptor_money_transfer_command_337c0a16c5e8f678 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc9, 0xcd, 0xcf, 0x4b,
	0xad, 0x8c, 0x2f, 0x29, 0x4a, 0xcc, 0x2b, 0x4e, 0x4b, 0x2d, 0x8a, 0x4f, 0xce, 0xcf, 0xcd, 0x4d,
	0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0xcb, 0x2a, 0x79, 0x73, 0x49,
	0xf8, 0x82, 0x18, 0x21, 0x50, 0x55, 0xc1, 0xa9, 0x79, 0x29, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0xe2, 0x5c, 0xec, 0xa5, 0xc5, 0xa9, 0x45, 0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x6c, 0x20, 0xae, 0x67, 0x8a, 0x90, 0x18, 0x17, 0x5b, 0x62, 0x6e, 0x7e, 0x69,
	0x5e, 0x89, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x94, 0xa7, 0x24, 0xcd, 0x25, 0x89, 0xc5,
	0xb0, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xa3, 0x44, 0x2e, 0x11, 0x14, 0x49, 0x67, 0x88, 0x73,
	0x84, 0x3c, 0xb9, 0x58, 0x40, 0xea, 0x84, 0xe4, 0xf5, 0xc0, 0x2e, 0xd2, 0xc3, 0xe5, 0x1c, 0x29,
	0x05, 0xdc, 0x0a, 0x20, 0x56, 0x38, 0xb1, 0x44, 0x31, 0x15, 0x24, 0x25, 0xb1, 0x81, 0x3d, 0x68,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xb9, 0x95, 0xa6, 0x00, 0x01, 0x00, 0x00,
}
