// Code generated by protoc-gen-go. DO NOT EDIT.
// source: money_command.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MoneyGainRequest struct {
	// ユーザーID
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 金額
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoneyGainRequest) Reset()         { *m = MoneyGainRequest{} }
func (m *MoneyGainRequest) String() string { return proto.CompactTextString(m) }
func (*MoneyGainRequest) ProtoMessage()    {}
func (*MoneyGainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_money_command_548f7d8482af7ef7, []int{0}
}
func (m *MoneyGainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoneyGainRequest.Unmarshal(m, b)
}
func (m *MoneyGainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoneyGainRequest.Marshal(b, m, deterministic)
}
func (dst *MoneyGainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoneyGainRequest.Merge(dst, src)
}
func (m *MoneyGainRequest) XXX_Size() int {
	return xxx_messageInfo_MoneyGainRequest.Size(m)
}
func (m *MoneyGainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoneyGainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoneyGainRequest proto.InternalMessageInfo

func (m *MoneyGainRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MoneyGainRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MoneyGainResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoneyGainResponse) Reset()         { *m = MoneyGainResponse{} }
func (m *MoneyGainResponse) String() string { return proto.CompactTextString(m) }
func (*MoneyGainResponse) ProtoMessage()    {}
func (*MoneyGainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_money_command_548f7d8482af7ef7, []int{1}
}
func (m *MoneyGainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoneyGainResponse.Unmarshal(m, b)
}
func (m *MoneyGainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoneyGainResponse.Marshal(b, m, deterministic)
}
func (dst *MoneyGainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoneyGainResponse.Merge(dst, src)
}
func (m *MoneyGainResponse) XXX_Size() int {
	return xxx_messageInfo_MoneyGainResponse.Size(m)
}
func (m *MoneyGainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoneyGainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoneyGainResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MoneyGainRequest)(nil), "money.MoneyGainRequest")
	proto.RegisterType((*MoneyGainResponse)(nil), "money.MoneyGainResponse")
}

func init() { proto.RegisterFile("money_command.proto", fileDescriptor_money_command_548f7d8482af7ef7) }

var fileDescriptor_money_command_548f7d8482af7ef7 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0xcd, 0xcf, 0x4b,
	0xad, 0x8c, 0x4f, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x05, 0x0b, 0x2a, 0x39, 0x73, 0x09, 0xf8, 0x82, 0x18, 0xee, 0x89, 0x99, 0x79, 0x41, 0xa9,
	0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0xe2, 0x5c, 0xec, 0xa5, 0xc5, 0xa9, 0x45, 0xf1, 0x99, 0x29,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x6c, 0x20, 0xae, 0x67, 0x8a, 0x90, 0x18, 0x17, 0x5b,
	0x62, 0x6e, 0x7e, 0x69, 0x5e, 0x89, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x94, 0xa7, 0x24,
	0xcc, 0x25, 0x88, 0x64, 0x48, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x91, 0x27, 0x17, 0x0f, 0x58,
	0xd0, 0x19, 0x62, 0xad, 0x90, 0x25, 0x17, 0x0b, 0x48, 0x5e, 0x48, 0x5c, 0x0f, 0x6c, 0xb3, 0x1e,
	0xba, 0xb5, 0x52, 0x12, 0x98, 0x12, 0x10, 0xa3, 0x9c, 0x58, 0xa2, 0x98, 0x0a, 0x92, 0x92, 0xd8,
	0xc0, 0x0e, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xda, 0xcc, 0x2e, 0xcf, 0x00, 0x00,
	0x00,
}
