// Code generated by protoc-gen-go. DO NOT EDIT.
// source: money_query.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MoneyGetBalanceRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoneyGetBalanceRequest) Reset()         { *m = MoneyGetBalanceRequest{} }
func (m *MoneyGetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*MoneyGetBalanceRequest) ProtoMessage()    {}
func (*MoneyGetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_money_query_6e9ed1822a09dfd8, []int{0}
}
func (m *MoneyGetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoneyGetBalanceRequest.Unmarshal(m, b)
}
func (m *MoneyGetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoneyGetBalanceRequest.Marshal(b, m, deterministic)
}
func (dst *MoneyGetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoneyGetBalanceRequest.Merge(dst, src)
}
func (m *MoneyGetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_MoneyGetBalanceRequest.Size(m)
}
func (m *MoneyGetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoneyGetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoneyGetBalanceRequest proto.InternalMessageInfo

func (m *MoneyGetBalanceRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type MoneyGetBalanceResponse struct {
	Balance              *Balance `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoneyGetBalanceResponse) Reset()         { *m = MoneyGetBalanceResponse{} }
func (m *MoneyGetBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*MoneyGetBalanceResponse) ProtoMessage()    {}
func (*MoneyGetBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_money_query_6e9ed1822a09dfd8, []int{1}
}
func (m *MoneyGetBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoneyGetBalanceResponse.Unmarshal(m, b)
}
func (m *MoneyGetBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoneyGetBalanceResponse.Marshal(b, m, deterministic)
}
func (dst *MoneyGetBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoneyGetBalanceResponse.Merge(dst, src)
}
func (m *MoneyGetBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_MoneyGetBalanceResponse.Size(m)
}
func (m *MoneyGetBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoneyGetBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoneyGetBalanceResponse proto.InternalMessageInfo

func (m *MoneyGetBalanceResponse) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

func init() {
	proto.RegisterType((*MoneyGetBalanceRequest)(nil), "money.MoneyGetBalanceRequest")
	proto.RegisterType((*MoneyGetBalanceResponse)(nil), "money.MoneyGetBalanceResponse")
}

func init() { proto.RegisterFile("money_query.proto", fileDescriptor_money_query_6e9ed1822a09dfd8) }

var fileDescriptor_money_query_6e9ed1822a09dfd8 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xcd, 0xcf, 0x4b,
	0xad, 0x8c, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x0b, 0x49, 0x09, 0x43, 0x64, 0x92, 0x12, 0x73, 0x12, 0xf3, 0x92, 0x53, 0x21, 0x72, 0x4a, 0x86,
	0x5c, 0x62, 0xbe, 0x20, 0x61, 0xf7, 0xd4, 0x12, 0x27, 0x88, 0x44, 0x50, 0x6a, 0x61, 0x69, 0x6a,
	0x71, 0x89, 0x90, 0x38, 0x17, 0x7b, 0x69, 0x71, 0x6a, 0x51, 0x7c, 0x66, 0x8a, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x1b, 0x88, 0xeb, 0x99, 0xa2, 0xe4, 0xcc, 0x25, 0x8e, 0xa1, 0xa5, 0xb8,
	0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x83, 0x8b, 0x1d, 0x6a, 0x3c, 0x58, 0x0f, 0xb7, 0x11, 0x9f,
	0x1e, 0xd8, 0x52, 0x3d, 0x98, 0x42, 0x98, 0xb4, 0x51, 0x24, 0x17, 0x17, 0xd8, 0x90, 0x40, 0x90,
	0x3b, 0x85, 0xbc, 0xb9, 0xb8, 0x10, 0xa6, 0x09, 0xc9, 0x42, 0x35, 0x61, 0x77, 0x98, 0x94, 0x1c,
	0x2e, 0x69, 0x88, 0x23, 0x9c, 0x58, 0xa2, 0x98, 0x0a, 0x92, 0x92, 0xd8, 0xc0, 0xfe, 0x33, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x69, 0xcc, 0xbc, 0xaf, 0x10, 0x01, 0x00, 0x00,
}
