// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserProfile          *Profile             `protobuf:"bytes,2,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_32ed2c2c295e686a, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUserProfile() *Profile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Profile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32   `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_32ed2c2c295e686a, []int{1}
}
func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (dst *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(dst, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Profile)(nil), "user.Profile")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_32ed2c2c295e686a) }

var fileDescriptor_user_32ed2c2c295e686a = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xc1, 0x4e, 0xc4, 0x20,
	0x10, 0x86, 0x03, 0x12, 0xcd, 0xce, 0xba, 0xc6, 0x70, 0x6a, 0xf6, 0xe2, 0xa6, 0xa7, 0x9e, 0xa8,
	0xd1, 0x93, 0xc7, 0xfa, 0x04, 0x86, 0xe8, 0xc5, 0x4b, 0x43, 0x65, 0xda, 0x90, 0xb4, 0x42, 0x28,
	0x7d, 0x3d, 0x9f, 0xcd, 0x00, 0xe5, 0xbc, 0xb7, 0x7f, 0x26, 0xdf, 0x3f, 0x7c, 0x00, 0x6c, 0x2b,
	0x7a, 0xe1, 0xbc, 0x0d, 0x96, 0xb3, 0x98, 0xcf, 0x4f, 0x93, 0xb5, 0xd3, 0x8c, 0x6d, 0xda, 0x0d,
	0xdb, 0xd8, 0x06, 0xb3, 0xe0, 0x1a, 0xd4, 0xe2, 0x32, 0x56, 0xff, 0x11, 0x60, 0x5f, 0x2b, 0x7a,
	0xfe, 0x00, 0xd4, 0xe8, 0x8a, 0x5c, 0x48, 0xc3, 0x24, 0x35, 0x9a, 0x3f, 0xc3, 0x7d, 0xbc, 0xd0,
	0x3b, 0x6f, 0x47, 0x33, 0x63, 0x45, 0x2f, 0xa4, 0x39, 0xbe, 0x9c, 0x44, 0x7a, 0xe2, 0x23, 0x2f,
	0xe5, 0x31, 0x4e, 0xfb, 0xc0, 0xdf, 0x00, 0x7e, 0x3c, 0xaa, 0x80, 0xba, 0x57, 0xa1, 0xd2, 0x89,
	0x3f, 0x8b, 0x2c, 0x20, 0x8a, 0x80, 0xf8, 0x2c, 0x02, 0xf2, 0xb0, 0xd3, 0x5d, 0x88, 0xd5, 0xcd,
	0xe9, 0x52, 0xc5, 0xeb, 0xd5, 0x9d, 0xee, 0x42, 0xdd, 0xc2, 0x5d, 0x11, 0xe0, 0xc0, 0x7e, 0xd5,
	0x82, 0xe9, 0x13, 0x07, 0x99, 0x32, 0x7f, 0x84, 0x1b, 0x35, 0x65, 0xfb, 0x93, 0x8c, 0xf1, 0x9d,
	0x7d, 0x53, 0x37, 0x0c, 0xb7, 0xe9, 0xea, 0xeb, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0x8b,
	0x21, 0x2e, 0x33, 0x01, 0x00, 0x00,
}
