// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_command.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserRegisterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_command_41916ff53734af91, []int{0}
}
func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (dst *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(dst, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

type UserRegisterResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterResponse) Reset()         { *m = UserRegisterResponse{} }
func (m *UserRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*UserRegisterResponse) ProtoMessage()    {}
func (*UserRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_command_41916ff53734af91, []int{1}
}
func (m *UserRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterResponse.Unmarshal(m, b)
}
func (m *UserRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterResponse.Marshal(b, m, deterministic)
}
func (dst *UserRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterResponse.Merge(dst, src)
}
func (m *UserRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_UserRegisterResponse.Size(m)
}
func (m *UserRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterResponse proto.InternalMessageInfo

func (m *UserRegisterResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserUpdateProfileRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32   `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateProfileRequest) Reset()         { *m = UserUpdateProfileRequest{} }
func (m *UserUpdateProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UserUpdateProfileRequest) ProtoMessage()    {}
func (*UserUpdateProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_command_41916ff53734af91, []int{2}
}
func (m *UserUpdateProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateProfileRequest.Unmarshal(m, b)
}
func (m *UserUpdateProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateProfileRequest.Marshal(b, m, deterministic)
}
func (dst *UserUpdateProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateProfileRequest.Merge(dst, src)
}
func (m *UserUpdateProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UserUpdateProfileRequest.Size(m)
}
func (m *UserUpdateProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateProfileRequest proto.InternalMessageInfo

func (m *UserUpdateProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserUpdateProfileRequest) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type UserUpdateProfileResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateProfileResponse) Reset()         { *m = UserUpdateProfileResponse{} }
func (m *UserUpdateProfileResponse) String() string { return proto.CompactTextString(m) }
func (*UserUpdateProfileResponse) ProtoMessage()    {}
func (*UserUpdateProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_command_41916ff53734af91, []int{3}
}
func (m *UserUpdateProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateProfileResponse.Unmarshal(m, b)
}
func (m *UserUpdateProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateProfileResponse.Marshal(b, m, deterministic)
}
func (dst *UserUpdateProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateProfileResponse.Merge(dst, src)
}
func (m *UserUpdateProfileResponse) XXX_Size() int {
	return xxx_messageInfo_UserUpdateProfileResponse.Size(m)
}
func (m *UserUpdateProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateProfileResponse proto.InternalMessageInfo

func (m *UserUpdateProfileResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*UserRegisterRequest)(nil), "user.UserRegisterRequest")
	proto.RegisterType((*UserRegisterResponse)(nil), "user.UserRegisterResponse")
	proto.RegisterType((*UserUpdateProfileRequest)(nil), "user.UserUpdateProfileRequest")
	proto.RegisterType((*UserUpdateProfileResponse)(nil), "user.UserUpdateProfileResponse")
}

func init() { proto.RegisterFile("user_command.proto", fileDescriptor_user_command_41916ff53734af91) }

var fileDescriptor_user_command_41916ff53734af91 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2d, 0x4e, 0x2d,
	0x8a, 0x4f, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x01, 0x89, 0x49, 0x71, 0x81, 0x48, 0x88, 0x88, 0x92, 0x28, 0x97, 0x70, 0x68, 0x71, 0x6a, 0x51,
	0x50, 0x6a, 0x7a, 0x66, 0x71, 0x09, 0x88, 0x2e, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x32, 0xe3, 0x12,
	0x41, 0x15, 0x2e, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x92, 0xe3, 0x02, 0x1b, 0x21, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x6d, 0xc4, 0xa5, 0x07, 0x36, 0x09, 0xac, 0x12, 0x2c, 0xae, 0xe4, 0xc0, 0x25,
	0x01, 0xe2, 0x85, 0x16, 0xa4, 0x24, 0x96, 0xa4, 0x06, 0x14, 0xe5, 0xa7, 0x65, 0xe6, 0xa4, 0x42,
	0xcd, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x05, 0xeb, 0xe5, 0x0c, 0x02, 0xb3, 0x85,
	0x04, 0xb8, 0x98, 0x13, 0xd3, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x78, 0x83, 0x40, 0x4c, 0x25,
	0x6b, 0x2e, 0x49, 0x2c, 0x26, 0x10, 0x67, 0xbd, 0xd1, 0x22, 0x46, 0x2e, 0x6e, 0x10, 0xd7, 0x19,
	0xe2, 0x6b, 0x21, 0x47, 0x2e, 0x0e, 0x98, 0x17, 0x84, 0x24, 0x91, 0x54, 0xa3, 0xfa, 0x56, 0x4a,
	0x0a, 0x9b, 0x14, 0xd4, 0xca, 0x00, 0x2e, 0x5e, 0x14, 0xb7, 0x08, 0xc9, 0x21, 0x14, 0x63, 0xf3,
	0xa6, 0x94, 0x3c, 0x4e, 0x79, 0x88, 0x89, 0x4e, 0x2c, 0x51, 0x4c, 0x05, 0x49, 0x49, 0x6c, 0xe0,
	0xf0, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x71, 0xb4, 0xbf, 0xa7, 0x01, 0x00, 0x00,
}
