// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/inari111/money-transfer/application/user"
	"github.com/inari111/money-transfer/domain"
	"github.com/inari111/money-transfer/handler"
	"github.com/inari111/money-transfer/infra/persistence/mysql"
	"github.com/inari111/money-transfer/infra/persistence/repository"
	"github.com/inari111/money-transfer/infra/rpc"
	"github.com/inari111/money-transfer/rpc/api"
	"net/http"
)

// Injectors from api.go:

func InitializeAPIHandler() http.Handler {
	transferRepository := repository.NewTransferRepository()
	moneyTransferCommand := api.NewMoneyTransferCommand(transferRepository)
	moneyQuery := rpc.NewMoneyQuery()
	dbMap := mysql.NewDbMap()
	userRepository := repository.NewUserRepository(dbMap)
	currentTimeFunc := domain.NewCurrentTimeFunc()
	profileRepository := repository.NewUserProfileRepository(dbMap, currentTimeFunc)
	application := user.NewApplication(userRepository, profileRepository, currentTimeFunc)
	userCommand := api.NewUserCommand(application)
	userQuery := rpc.NewUserQuery()
	moneyCommand := api.NewMoneyCommand()
	httpHandler := handler.NewHandler(moneyTransferCommand, moneyQuery, userCommand, userQuery, moneyCommand)
	return httpHandler
}
